###

POST http://localhost:1500/api/courses
Content-Type: application/json

{
    "tema": "Prompt Engineering",
    "nombre": "ChatGPT Complete Course - Prompt Engineering for ChatGPTI",
    "duracion": "7.5h",
    "nivel": "Intermedio"
}



###
GET http://localhost:1500/api/courses HTTP/1.1

