###

POST http://localhost:1500/api/users
Content-Type: application/json

{
    "name": "Claudio Sabillon",
    "email": "claudio@neoris.com",
    "password": "password",
    "rol": "estudiante"
}



###
GET http://localhost:1500/api/users HTTP/1.1

